# Generated by Django 4.2 on 2024-10-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0002_member_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_address',
            field=models.CharField(default='@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
