# Generated by Django 4.2 on 2024-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0003_member_email_address_alter_member_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
