# Generated by Django 4.2 on 2024-10-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0004_alter_member_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
