# Generated by Django 4.2 on 2024-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0005_alter_member_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
