# Generated by Django 4.2 on 2024-10-28 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0008_member_active_member_phone_number_member_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='start_date',
            field=models.DateField(null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
