# Generated by Django 4.2 on 2024-10-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0009_member_end_date_member_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('detail', models.TextField()),
                ('img', models.ImageField(upload_to='trainers/')),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
