# Generated by Django 4.2 on 2024-10-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0010_trainer_alter_member_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='img',
        ),
        migrations.AddField(
            model_name='trainer',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
