# Generated by Django 4.2 on 2024-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0011_remove_trainer_detail_remove_trainer_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email_address', models.CharField(max_length=50, null=True)),
                ('message', models.TextField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trainer',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
