# Generated by Django 4.2 on 2024-10-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0012_notifications_alter_trainer_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
