# Generated by Django 4.2 on 2024-10-30 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0014_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=datetime.time(17, 11, 11, 716166)),
        ),
    ]
